# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  database:
    url: sqlite://./data.db
llm:
  models:
  - name: trend-pro
    provider: openAI
    params:
      baseUrl: $LLM_BASE_URL
      model: $LLM_MODEL
      apiKey: ollama-does-not-check-this
mcp:
  targets:
  - name: github
    openapi:
      host: https://api.github.com
      schema:
        file: configs/github-search.openapi.json