# yaml-language-server: $schema=https://agentgateway.dev/schema/config
config:
  database:
    url: sqlite://./data.db
llm:
  policies:
    localRateLimit:
    - maxTokens: 5000
      tokensPerFill: 5000
      fillInterval: 300s
      type: tokens
  models:
  - name: trend-pro
    provider: openAI
    params:
      baseUrl: $LLM_BASE_URL
      model: $LLM_MODEL
      apiKey: ollama-does-not-check-this